PKGDIR       ?= ..
L4DIR        ?= $(PKGDIR)/../../..

TARGET        = libssd1306.a libssd1306.so
SRC_CC        = ssd1306.cc
PC_FILENAME   = ssd1306
REQUIRES_LIBS = libstdc++ spi-driver libio-vbus

include $(L4DIR)/mk/lib.mk
