PKGDIR       ?= ../..
L4DIR        ?= $(PKGDIR)/../..

TARGET	      = libspi-server.a libspi-server.so
SRC_CC        = spi_server.cc
PC_FILENAME   = spi-server
REQUIRES_LIBS = libstdc++ l4virtio

include $(L4DIR)/mk/lib.mk
