PKGDIR       ?= ..
L4DIR        ?= $(PKGDIR)/../../..

TARGET        = libat24c02.a libat24c02.so
SRC_CC        = at24c02.cc
PC_FILENAME   = at24c02
REQUIRES_LIBS = libstdc++ i2c-server

include $(L4DIR)/mk/lib.mk
