PKGDIR		?= ..
L4DIR		?= $(PKGDIR)/../../../..

TARGET		= usb-drv

# list your .c or .cc files here
SRC_CC          = main.cc hc.cc server.cc ohci.cc 

# list requirements of your program here
REQUIRES_LIBS   = libstdc++ libio

include $(L4DIR)/mk/prog.mk
