PKGDIR       ?= ..
L4DIR        ?= $(PKGDIR)/../../..

TARGET        = libtef6686hn.a libtef6686hn.so
SRC_CC        = tef6686hn.cc
PC_FILENAME   = tef6686hn
REQUIRES_LIBS = libstdc++ i2c-server

include $(L4DIR)/mk/lib.mk
