PKGDIR      ?= ../..
L4DIR       ?= $(PKGDIR)/../..

CONTRIB_HEADERS = y
INCSRC_DIR      = $(SRC_DIR)/../../contrib/include
TARGET          = ext4.h ext4_blockdev.h ext4_errno.h ext4_oflags.h \
                  ext4_config.h ext4_types.h ext4_mbr.h ext4_mkfs.h \
                  ext4_debug.h ext4_misc.h

include $(L4DIR)/mk/include.mk
