PKGDIR       ?= ..
L4DIR        ?= $(PKGDIR)/../../..

TARGET        = libmcp2515.a libmcp2515.so
SRC_CC        = mcp2515.cc
PC_FILENAME   = mcp2515
REQUIRES_LIBS = libstdc++ spi-server

include $(L4DIR)/mk/lib.mk
