PKGDIR       ?= ..
L4DIR        ?= $(PKGDIR)/../../..

TARGET        = libds18b20.a libds18b20.so
SRC_CC        = ds18b20.cc
PC_FILENAME   = ds18b20
REQUIRES_LIBS = libstdc++ libio-vbus l4util

include $(L4DIR)/mk/lib.mk
