PKGDIR		?= ..
L4DIR		?= $(PKGDIR)/../..

TARGET		= exectest
SRC_CC		= main.cc

PRIVATE_INCDIR += $(SRC_DIR)/../../spawn/include

REQUIRES_LIBS	= libstdc++ l4re l4re_c l4util

include $(L4DIR)/mk/prog.mk
